cc_test (
    name = "square_intersection_tests",
    srcs = [
        "square_intersection_tests.cpp",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//src:square_intersection"
    ],
)